### ISSUE TITLE
help wanted

### ISSUE THREAD

**Issue by niskepaz** [Astron-fjh/Cordic-calculator#1]
Hi, ive been going through your project, and Im currently trying to verify the cordic_sin_cos module. I noticed that the simulation screenshot is included, but the testbench code used to generate it seems to be missing from the files.

The simulation screenshot is super helpful, but having the actual testbench code would make it much easier to replicate the results and verify the module. Would it be possible for you to share it?

**Comment by Astron-fjh** [comment]
Hi, the testbench code in the simulation screenshot is in this directory: Cordic_calculator_base/Cordic_calculator.srcs/sim_1/new/testbench.v

**Comment by Astron-fjh** [comment]
> Hi, ive been going through your project, and Im currently trying to verify the cordic_sin_cos module. I noticed that the simulation screenshot is included, but the testbench code used to generate it seems to be missing from the files.
> 
> The simulation screenshot is super helpful, but having the actual testbench code would make it much easier to replicate the results and verify the module. Would it be possible for you to share it?

Hi, the testbench code in the simulation screenshot is in this directory: Cordic_calculator_base/Cordic_calculator.srcs/sim_1/new/testbench.v

**Comment by niskepaz** [comment]
However, I noticed that the testbench code in the file you mentioned doesnt match the one shown in the simulation screenshot you shared. Heres the screenshot(
![image](https://github.com/user-attachments/assets/19ad1dda-9981-4e95-8f6f-f5305725192e)
) of the testbench I’m referring to, but it seems different from what’s described in section 4.1.
![image](https://github.com/user-attachments/assets/272a49b1-4784-4990-823f-219311920a2b)

**Comment by Astron-fjh** [comment]
> However, I noticed that the testbench code in the file you mentioned doesnt match the one shown in the simulation screenshot you shared. Heres the screenshot( ![image](https://private-user-images.githubusercontent.com/191245681/394309722-19ad1dda-9981-4e95-8f6f-f5305725192e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4NDA5NjYsIm5iZiI6MTczMzg0MDY2NiwicGF0aCI6Ii8xOTEyNDU2ODEvMzk0MzA5NzIyLTE5YWQxZGRhLTk5ODEtNGU5NS04ZjZmLWY1MzA1NzI1MTkyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMFQxNDI0MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOWFhZTA5N2UwM2I4NTM5YmMzNzg2ZDM1MGFkODQ0ZjM0OGRlMGE2ODM5NmVkN2QzOGEwY2RmMzdlMzdhM2IwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QV2NziFH2-Se9cMMEnILpiJdLqOmqB08usMuYceWEac) ) of the testbench I’m referring to, but it seems different from what’s described in section 4.1. ![image](https://private-user-images.githubusercontent.com/191245681/394309801-272a49b1-4784-4990-823f-219311920a2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4NDA5NjYsIm5iZiI6MTczMzg0MDY2NiwicGF0aCI6Ii8xOTEyNDU2ODEvMzk0MzA5ODAxLTI3MmE0OWIxLTQ3ODQtNDk5MC04MjNmLTIxOTMxMTkyMGEyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMFQxNDI0MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZGIzN2Q2MjY2MGQzNjc3OTliZDQ4ODgzOTdiYTBhNGVkMTA5ZDRlNzA0MTI1ZTY1M2JiODg0ZGZjNmM3NGYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TakLrSfSu32Xrgncvgm1rTlnrH-elkWQqVJy8t0_wIM)
If you're referring to the difference in simulation interfaces, it's because I used Vivado and ModelSim for co-simulation. The screenshot you see is from the ModelSim interface. If your concern is about differences in simulation results, I suggest selecting the relevant signals in the corresponding module within Vivado to verify the results. I hope this clarifies your question.

**Comment by Astron-fjh** [comment]
> However, I noticed that the testbench code in the file you mentioned doesnt match the one shown in the simulation screenshot you shared. Heres the screenshot( ![image](https://private-user-images.githubusercontent.com/191245681/394309722-19ad1dda-9981-4e95-8f6f-f5305725192e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4NDA5NjYsIm5iZiI6MTczMzg0MDY2NiwicGF0aCI6Ii8xOTEyNDU2ODEvMzk0MzA5NzIyLTE5YWQxZGRhLTk5ODEtNGU5NS04ZjZmLWY1MzA1NzI1MTkyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMFQxNDI0MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOWFhZTA5N2UwM2I4NTM5YmMzNzg2ZDM1MGFkODQ0ZjM0OGRlMGE2ODM5NmVkN2QzOGEwY2RmMzdlMzdhM2IwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QV2NziFH2-Se9cMMEnILpiJdLqOmqB08usMuYceWEac) ) of the testbench I’m referring to, but it seems different from what’s described in section 4.1. ![image](https://private-user-images.githubusercontent.com/191245681/394309801-272a49b1-4784-4990-823f-219311920a2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4NDA5NjYsIm5iZiI6MTczMzg0MDY2NiwicGF0aCI6Ii8xOTEyNDU2ODEvMzk0MzA5ODAxLTI3MmE0OWIxLTQ3ODQtNDk5MC04MjNmLTIxOTMxMTkyMGEyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMFQxNDI0MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZGIzN2Q2MjY2MGQzNjc3OTliZDQ4ODgzOTdiYTBhNGVkMTA5ZDRlNzA0MTI1ZTY1M2JiODg0ZGZjNmM3NGYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TakLrSfSu32Xrgncvgm1rTlnrH-elkWQqVJy8t0_wIM)

If you're referring to the difference in simulation interfaces, it's because I used Vivado and ModelSim for co-simulation. The screenshot you see is from the ModelSim interface. If your concern is about differences in simulation results, I suggest selecting the relevant signals in the corresponding module within Vivado to verify the results. I hope this clarifies your question.

**Comment by niskepaz** [comment]
Thought testbench for the provided screenshot with all the signals would be included in the attachments. Appreciate the clarification
